// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal.Data;


#nullable disable

namespace ProyectoFinal.Migrations
{
    [DbContext(typeof(BingoContext))]
    [Migration("20230131211514_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinal.Data.HistorialBolillero", b =>
                {
                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroBolilla")
                        .HasColumnType("int");

                    b.HasKey("FechaHora");

                    b.ToTable("HistorialBolilleros");
                });

            modelBuilder.Entity("ProyectoFinal.Data.HistorialCartones", b =>
                {
                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Carton1")
                        .HasColumnType("int");

                    b.Property<int?>("Carton2")
                        .HasColumnType("int");

                    b.Property<int?>("Carton3")
                        .HasColumnType("int");

                    b.Property<int?>("Carton4")
                        .HasColumnType("int");

                    b.HasKey("FechaHora");

                    b.ToTable("HistorialCartones");
                });
#pragma warning restore 612, 618
        }
    }
}
